services:
  - type: web
    name: camp-scheduler
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        value: nikesoccer2025
      - key: DATABASE_URL
        fromDatabase:
          name: camp-scheduler-db
          property: connectionString
      - key: GMAIL_USER
        value: rich.seattlesoccer@gmail.com
      - key: GMAIL_APP_PASSWORD
        value: guiplunclnwnqqby
      - key: TWILIO_ACCOUNT_SID
        value: ""
      - key: TWILIO_AUTH_TOKEN
        value: ""
      - key: TWILIO_FROM_NUMBER
        value: ""

databases:
  - name: camp-scheduler-db
    plan: free
