name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -s "https://api.render.com/deploy/srv-d88j0vv7f7vs73b9evr0?key=mrS3bd8l6Ho"
